name: Setup Node

description: Setup Node

on:
  workflow_call:
    inputs:
      NPM_AUTH_TOKEN:
        required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Yarn
      run: yarn
      shell: bash
