name: Setup Bun

description: Setup Bun

on:
  workflow_call:
    inputs:
      NPM_AUTH_TOKEN:
        required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: bun install
      shell: bash
