name: build storybook and deploy
env:
  VERCEL_PROJECT_ID: prj_X4CMVtNZggS7o95Iey4AWLkX1oH7
  APP_ENV: production

on:
  workflow_call:
    secrets:
      VERCEL_TOKEN:
        required: true

jobs:
  build-and-deploy-to-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: ./.github/actions/setup-bun
      - name: Pull Vercel Environment Information
        run: bun vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Storybook Artifacts
        run: bun build-storybook
      - name: Deploy Storybook Artifacts to Vercel
        run: bun vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --regions icn1
