name: pull request preview

on: pull_request

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/workflow-lint-check.yml

  test:
    uses: ./.github/workflows/workflow-test-check.yml

  build-and-deploy-storybook:
    needs: lint
    uses: ./.github/workflows/workflow-build-and-deploy-storybook.yml
    with:
      branch: ${{ github.head_ref }}
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  build-and-deploy-coverage:
    needs: test
    uses: ./.github/workflows/workflow-build-and-deploy-coverage.yml
    with:
      branch: ${{ github.head_ref }}
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  comment-on-pr:
    if: ${{ always() }}
    needs: [build-and-deploy-storybook, build-and-deploy-coverage]
    uses: ./.github/workflows/workflow-comment-summary.yml
    with:
      storybook-deploy-url: ${{ needs.build-and-deploy-storybook.outputs.url }}
      coverage-deploy-url: ${{ needs.build-and-deploy-coverage.outputs.url }}
