name: pull request preview

on: pull_request

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/workflow-lint-check.yml

  build-and-deploy-preview:
    needs: lint
    uses: ./.github/workflows/workflow-build-and-deploy-preview.yml
    with:
      branch: ${{ github.head_ref }}
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

  build-and-deploy-storybook:
    needs: lint
    uses: ./.github/workflows/workflow-build-and-deploy-storybook.yml
    with:
      branch: ${{ github.head_ref }}
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

  comment-on-pr:
    if: ${{ always() }}
    needs: [build-and-deploy-preview, build-and-deploy-storybook]
    uses: ./.github/workflows/workflow-comment-summary.yml
    with:
      preview-deploy-url: ${{ needs.build-and-deploy-preview.outputs.url }}
      storybook-deploy-url: ${{ needs.build-and-deploy-storybook.outputs.url }}
