name: push main

on:
  push:
    branches:
      - main

concurrency:
  group: web-deploy
  cancel-in-progress: true

jobs:
  build-and-deploy-storybook:
    uses: ./.github/workflows/workflow-build-and-deploy-storybook.yml
    with:
      branch: main
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  build-and-deploy-coverage:
    uses: ./.github/workflows/workflow-build-and-deploy-coverage.yml
    with:
      branch: main
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

