name: build preview and deploy
env:
  VERCEL_PROJECT_ID: prj_eG0t2rI3ZtPIQAq8HGz45FA3qS59
  APP_ENV: development

on:
  workflow_call:
    secrets:
      VERCEL_TOKEN:
        required: true

    outputs:
      url:
        description: 'Deployed preview url (by commit)'
        value: ${{ jobs.build-and-deploy-to-vercel.outputs.DEPLOYMENT_URL }}

jobs:
  build-and-deploy-to-vercel:
    runs-on: [self-hosted, linux, X64]
    outputs:
      DEPLOYMENT_URL: ${{ steps.deploy-to-vercel.outputs.DEPLOYMENT_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: ./.github/actions/setup-bun
      - name: Pull Vercel Environment Information
        run: bun vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: bun vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        id: deploy-to-vercel
        run: DEPLOYMENT_URL=$(bun vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --regions icn1) && echo "DEPLOYMENT_URL=$DEPLOYMENT_URL" >> "$GITHUB_OUTPUT"
      - name: Set Branch Name for URL
        id: set-branch-name
        run: |
          BRANCH_NAME=$(echo ${GITHUB_HEAD_REF:-$(git symbolic-ref --short HEAD)} | tr '[:upper:]' '[:lower:]' | sed -e 's/[^[:alnum:]-]/-/g' | cut -c 1-50) && echo "BRANCH_NAME=$BRANCH_NAME" >> "$GITHUB_OUTPUT"
      - name: Alias Preview Url
        run: bun vercel alias --token=${{ secrets.VERCEL_TOKEN }} set "${{ steps.deploy-to-vercel.outputs.DEPLOYMENT_URL }}" "${{ steps.set-branch-name.outputs.BRANCH_NAME }}-nonamep765-web.vercel.app"
