name: lint check

on: workflow_call

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup bun
        uses: ./.github/actions/setup-bun

      - name: Run Lint
        run: bun lint
